package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.A;
import com.example.infoRetrieval.pojo.AExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int countByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int deleteByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insertSelective(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    List<A> selectByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") A record, @Param("example") AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExample(@Param("record") A record, @Param("example") AExample example);
}