package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Goodexistdou;
import com.example.infoRetrieval.pojo.GoodexistdouExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodexistdouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int countByExample(GoodexistdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int deleteByExample(GoodexistdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insert(Goodexistdou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insertSelective(Goodexistdou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    List<Goodexistdou> selectByExample(GoodexistdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Goodexistdou record, @Param("example") GoodexistdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExample(@Param("record") Goodexistdou record, @Param("example") GoodexistdouExample example);
}