package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Goodexistsingle;
import com.example.infoRetrieval.pojo.GoodexistsingleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodexistsingleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int countByExample(GoodexistsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int deleteByExample(GoodexistsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insert(Goodexistsingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insertSelective(Goodexistsingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    List<Goodexistsingle> selectByExample(GoodexistsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Goodexistsingle record, @Param("example") GoodexistsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodexistsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExample(@Param("record") Goodexistsingle record, @Param("example") GoodexistsingleExample example);
}