package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Lyrics;
import com.example.infoRetrieval.pojo.LyricsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LyricsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int countByExample(LyricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int deleteByExample(LyricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int insert(Lyrics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int insertSelective(Lyrics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    List<Lyrics> selectByExample(LyricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Lyrics record, @Param("example") LyricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyrics
     *
     * @mbggenerated Sun Jun 03 23:06:25 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Lyrics record, @Param("example") LyricsExample example);

    String selectByDoc(String doc);

    List<Lyrics> selectByAll();
}