package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.PermIndex;
import com.example.infoRetrieval.pojo.PermIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int countByExample(PermIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int deleteByExample(PermIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String varia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int insert(PermIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int insertSelective(PermIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    List<PermIndex> selectByExample(PermIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    PermIndex selectByPrimaryKey(String varia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") PermIndex record, @Param("example") PermIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int updateByExample(@Param("record") PermIndex record, @Param("example") PermIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(PermIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    int updateByPrimaryKey(PermIndex record);
    List<PermIndex> getAll();
}