package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Raw;
import com.example.infoRetrieval.pojo.RawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int countByExample(RawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int deleteByExample(RawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int insert(Raw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int insertSelective(Raw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    List<Raw> selectByExample(RawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Raw record, @Param("example") RawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Raw record, @Param("example") RawExample example);
}