package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Smoothsingle;
import com.example.infoRetrieval.pojo.SmoothsingleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmoothsingleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int countByExample(SmoothsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int deleteByExample(SmoothsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insert(Smoothsingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int insertSelective(Smoothsingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    List<Smoothsingle> selectByExample(SmoothsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Smoothsingle record, @Param("example") SmoothsingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothsingle
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    int updateByExample(@Param("record") Smoothsingle record, @Param("example") SmoothsingleExample example);
}