package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Smoothdou;
import com.example.infoRetrieval.pojo.SmoothdouExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmoothdouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int countByExample(SmoothdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int deleteByExample(SmoothdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int insert(Smoothdou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int insertSelective(Smoothdou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    List<Smoothdou> selectByExample(SmoothdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Smoothdou record, @Param("example") SmoothdouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    int updateByExample(@Param("record") Smoothdou record, @Param("example") SmoothdouExample example);
}