package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.Stemmer;
import com.example.infoRetrieval.pojo.StemmerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StemmerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int countByExample(StemmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int deleteByExample(StemmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int deleteByPrimaryKey(String varia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int insert(Stemmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int insertSelective(Stemmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    List<Stemmer> selectByExample(StemmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    Stemmer selectByPrimaryKey(String varia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Stemmer record, @Param("example") StemmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int updateByExample(@Param("record") Stemmer record, @Param("example") StemmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int updateByPrimaryKeySelective(Stemmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stemmer
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    int updateByPrimaryKey(Stemmer record);
}