package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.StopTerm;
import com.example.infoRetrieval.pojo.StopTermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StopTermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int countByExample(StopTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int deleteByExample(StopTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int insert(StopTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int insertSelective(StopTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    List<StopTerm> selectByExample(StopTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") StopTerm record, @Param("example") StopTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    int updateByExample(@Param("record") StopTerm record, @Param("example") StopTermExample example);
     List<StopTerm> selectLike(@Param("a")String a);
}