package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.WfTbl;
import com.example.infoRetrieval.pojo.WfTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int countByExample(WfTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int deleteByExample(WfTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int insert(WfTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int insertSelective(WfTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    List<WfTbl> selectByExample(WfTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") WfTbl record, @Param("example") WfTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int updateByExample(@Param("record") WfTbl record, @Param("example") WfTblExample example);
    List<WfTbl> selectByDoc(String doc);
}