package com.example.infoRetrieval.dao;

import com.example.infoRetrieval.pojo.WTbl;
import com.example.infoRetrieval.pojo.WTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int countByExample(WTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int deleteByExample(WTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int insert(WTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int insertSelective(WTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    List<WTbl> selectByExample(WTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") WTbl record, @Param("example") WTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_tbl
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    int updateByExample(@Param("record") WTbl record, @Param("example") WTblExample example);
    List<WTbl> selectByDoc(String doc);
}