package com.example.infoRetrieval.pojo;

public class AfterIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_index.Term
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    private String term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_index.N_docs
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    private Integer nDocs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_index.freq
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    private Integer freq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_index.Term
     *
     * @return the value of after_index.Term
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_index.Term
     *
     * @param term the value for after_index.Term
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_index.N_docs
     *
     * @return the value of after_index.N_docs
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public Integer getnDocs() {
        return nDocs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_index.N_docs
     *
     * @param nDocs the value for after_index.N_docs
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public void setnDocs(Integer nDocs) {
        this.nDocs = nDocs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_index.freq
     *
     * @return the value of after_index.freq
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_index.freq
     *
     * @param freq the value for after_index.freq
     *
     * @mbggenerated Tue May 01 12:50:14 CST 2018
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }
}