package com.example.infoRetrieval.pojo;

public class BeforeIndex extends BeforeIndexKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column before_index.freq
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    private Integer freq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column before_index.freq
     *
     * @return the value of before_index.freq
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column before_index.freq
     *
     * @param freq the value for before_index.freq
     *
     * @mbggenerated Sun Apr 29 13:37:54 GMT+08:00 2018
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }
}