package com.example.infoRetrieval.pojo;

public class Countdou {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countdou.wi1
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    private String wi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countdou.wi
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    private String wi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countdou.doc
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    private String doc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countdou.freq
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    private Integer freq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countdou.wi1
     *
     * @return the value of countdou.wi1
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public String getWi1() {
        return wi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countdou.wi1
     *
     * @param wi1 the value for countdou.wi1
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public void setWi1(String wi1) {
        this.wi1 = wi1 == null ? null : wi1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countdou.wi
     *
     * @return the value of countdou.wi
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public String getWi() {
        return wi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countdou.wi
     *
     * @param wi the value for countdou.wi
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public void setWi(String wi) {
        this.wi = wi == null ? null : wi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countdou.doc
     *
     * @return the value of countdou.doc
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public String getDoc() {
        return doc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countdou.doc
     *
     * @param doc the value for countdou.doc
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public void setDoc(String doc) {
        this.doc = doc == null ? null : doc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column countdou.freq
     *
     * @return the value of countdou.freq
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column countdou.freq
     *
     * @param freq the value for countdou.freq
     *
     * @mbggenerated Sat Jun 02 23:00:51 CST 2018
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }
}