package com.example.infoRetrieval.pojo;

public class Goodexistdou {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodexistdou.wi1
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    private String wi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodexistdou.wi
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    private String wi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodexistdou.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    private Float p;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodexistdou.wi1
     *
     * @return the value of goodexistdou.wi1
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public String getWi1() {
        return wi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodexistdou.wi1
     *
     * @param wi1 the value for goodexistdou.wi1
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setWi1(String wi1) {
        this.wi1 = wi1 == null ? null : wi1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodexistdou.wi
     *
     * @return the value of goodexistdou.wi
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public String getWi() {
        return wi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodexistdou.wi
     *
     * @param wi the value for goodexistdou.wi
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setWi(String wi) {
        this.wi = wi == null ? null : wi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodexistdou.P
     *
     * @return the value of goodexistdou.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public Float getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodexistdou.P
     *
     * @param p the value for goodexistdou.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setP(Float p) {
        this.p = p;
    }
}