package com.example.infoRetrieval.pojo;

public class Goodexistsingle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodexistsingle.term
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    private String term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodexistsingle.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    private Float p;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodexistsingle.term
     *
     * @return the value of goodexistsingle.term
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodexistsingle.term
     *
     * @param term the value for goodexistsingle.term
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodexistsingle.P
     *
     * @return the value of goodexistsingle.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public Float getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodexistsingle.P
     *
     * @param p the value for goodexistsingle.P
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setP(Float p) {
        this.p = p;
    }
}