package com.example.infoRetrieval.pojo;

import java.util.ArrayList;
import java.util.List;

public class PermIndexExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public PermIndexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVariaIsNull() {
            addCriterion("varia is null");
            return (Criteria) this;
        }

        public Criteria andVariaIsNotNull() {
            addCriterion("varia is not null");
            return (Criteria) this;
        }

        public Criteria andVariaEqualTo(String value) {
            addCriterion("varia =", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaNotEqualTo(String value) {
            addCriterion("varia <>", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaGreaterThan(String value) {
            addCriterion("varia >", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaGreaterThanOrEqualTo(String value) {
            addCriterion("varia >=", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaLessThan(String value) {
            addCriterion("varia <", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaLessThanOrEqualTo(String value) {
            addCriterion("varia <=", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaLike(String value) {
            addCriterion("varia like", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaNotLike(String value) {
            addCriterion("varia not like", value, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaIn(List<String> values) {
            addCriterion("varia in", values, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaNotIn(List<String> values) {
            addCriterion("varia not in", values, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaBetween(String value1, String value2) {
            addCriterion("varia between", value1, value2, "varia");
            return (Criteria) this;
        }

        public Criteria andVariaNotBetween(String value1, String value2) {
            addCriterion("varia not between", value1, value2, "varia");
            return (Criteria) this;
        }

        public Criteria andProtoIsNull() {
            addCriterion("proto is null");
            return (Criteria) this;
        }

        public Criteria andProtoIsNotNull() {
            addCriterion("proto is not null");
            return (Criteria) this;
        }

        public Criteria andProtoEqualTo(String value) {
            addCriterion("proto =", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoNotEqualTo(String value) {
            addCriterion("proto <>", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoGreaterThan(String value) {
            addCriterion("proto >", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoGreaterThanOrEqualTo(String value) {
            addCriterion("proto >=", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoLessThan(String value) {
            addCriterion("proto <", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoLessThanOrEqualTo(String value) {
            addCriterion("proto <=", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoLike(String value) {
            addCriterion("proto like", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoNotLike(String value) {
            addCriterion("proto not like", value, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoIn(List<String> values) {
            addCriterion("proto in", values, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoNotIn(List<String> values) {
            addCriterion("proto not in", values, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoBetween(String value1, String value2) {
            addCriterion("proto between", value1, value2, "proto");
            return (Criteria) this;
        }

        public Criteria andProtoNotBetween(String value1, String value2) {
            addCriterion("proto not between", value1, value2, "proto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perm_index
     *
     * @mbggenerated do_not_delete_during_merge Sun May 06 17:07:00 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perm_index
     *
     * @mbggenerated Sun May 06 17:07:00 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}