package com.example.infoRetrieval.pojo;

public class Smoothdou {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoothdou.wi1
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    private String wi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoothdou.wi
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    private String wi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoothdou.doc
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    private String doc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoothdou.freq
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    private Float freq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoothdou.wi1
     *
     * @return the value of smoothdou.wi1
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public String getWi1() {
        return wi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoothdou.wi1
     *
     * @param wi1 the value for smoothdou.wi1
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public void setWi1(String wi1) {
        this.wi1 = wi1 == null ? null : wi1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoothdou.wi
     *
     * @return the value of smoothdou.wi
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public String getWi() {
        return wi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoothdou.wi
     *
     * @param wi the value for smoothdou.wi
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public void setWi(String wi) {
        this.wi = wi == null ? null : wi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoothdou.doc
     *
     * @return the value of smoothdou.doc
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public String getDoc() {
        return doc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoothdou.doc
     *
     * @param doc the value for smoothdou.doc
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public void setDoc(String doc) {
        this.doc = doc == null ? null : doc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoothdou.freq
     *
     * @return the value of smoothdou.freq
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public Float getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoothdou.freq
     *
     * @param freq the value for smoothdou.freq
     *
     * @mbggenerated Sun Jun 03 14:38:47 CST 2018
     */
    public void setFreq(Float freq) {
        this.freq = freq;
    }
}