package com.example.infoRetrieval.pojo;

import java.util.ArrayList;
import java.util.List;

public class SmoothdouExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public SmoothdouExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWi1IsNull() {
            addCriterion("wi1 is null");
            return (Criteria) this;
        }

        public Criteria andWi1IsNotNull() {
            addCriterion("wi1 is not null");
            return (Criteria) this;
        }

        public Criteria andWi1EqualTo(String value) {
            addCriterion("wi1 =", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1NotEqualTo(String value) {
            addCriterion("wi1 <>", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1GreaterThan(String value) {
            addCriterion("wi1 >", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1GreaterThanOrEqualTo(String value) {
            addCriterion("wi1 >=", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1LessThan(String value) {
            addCriterion("wi1 <", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1LessThanOrEqualTo(String value) {
            addCriterion("wi1 <=", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1Like(String value) {
            addCriterion("wi1 like", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1NotLike(String value) {
            addCriterion("wi1 not like", value, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1In(List<String> values) {
            addCriterion("wi1 in", values, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1NotIn(List<String> values) {
            addCriterion("wi1 not in", values, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1Between(String value1, String value2) {
            addCriterion("wi1 between", value1, value2, "wi1");
            return (Criteria) this;
        }

        public Criteria andWi1NotBetween(String value1, String value2) {
            addCriterion("wi1 not between", value1, value2, "wi1");
            return (Criteria) this;
        }

        public Criteria andWiIsNull() {
            addCriterion("wi is null");
            return (Criteria) this;
        }

        public Criteria andWiIsNotNull() {
            addCriterion("wi is not null");
            return (Criteria) this;
        }

        public Criteria andWiEqualTo(String value) {
            addCriterion("wi =", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiNotEqualTo(String value) {
            addCriterion("wi <>", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiGreaterThan(String value) {
            addCriterion("wi >", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiGreaterThanOrEqualTo(String value) {
            addCriterion("wi >=", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiLessThan(String value) {
            addCriterion("wi <", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiLessThanOrEqualTo(String value) {
            addCriterion("wi <=", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiLike(String value) {
            addCriterion("wi like", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiNotLike(String value) {
            addCriterion("wi not like", value, "wi");
            return (Criteria) this;
        }

        public Criteria andWiIn(List<String> values) {
            addCriterion("wi in", values, "wi");
            return (Criteria) this;
        }

        public Criteria andWiNotIn(List<String> values) {
            addCriterion("wi not in", values, "wi");
            return (Criteria) this;
        }

        public Criteria andWiBetween(String value1, String value2) {
            addCriterion("wi between", value1, value2, "wi");
            return (Criteria) this;
        }

        public Criteria andWiNotBetween(String value1, String value2) {
            addCriterion("wi not between", value1, value2, "wi");
            return (Criteria) this;
        }

        public Criteria andDocIsNull() {
            addCriterion("doc is null");
            return (Criteria) this;
        }

        public Criteria andDocIsNotNull() {
            addCriterion("doc is not null");
            return (Criteria) this;
        }

        public Criteria andDocEqualTo(String value) {
            addCriterion("doc =", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocNotEqualTo(String value) {
            addCriterion("doc <>", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocGreaterThan(String value) {
            addCriterion("doc >", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocGreaterThanOrEqualTo(String value) {
            addCriterion("doc >=", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocLessThan(String value) {
            addCriterion("doc <", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocLessThanOrEqualTo(String value) {
            addCriterion("doc <=", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocLike(String value) {
            addCriterion("doc like", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocNotLike(String value) {
            addCriterion("doc not like", value, "doc");
            return (Criteria) this;
        }

        public Criteria andDocIn(List<String> values) {
            addCriterion("doc in", values, "doc");
            return (Criteria) this;
        }

        public Criteria andDocNotIn(List<String> values) {
            addCriterion("doc not in", values, "doc");
            return (Criteria) this;
        }

        public Criteria andDocBetween(String value1, String value2) {
            addCriterion("doc between", value1, value2, "doc");
            return (Criteria) this;
        }

        public Criteria andDocNotBetween(String value1, String value2) {
            addCriterion("doc not between", value1, value2, "doc");
            return (Criteria) this;
        }

        public Criteria andFreqIsNull() {
            addCriterion("freq is null");
            return (Criteria) this;
        }

        public Criteria andFreqIsNotNull() {
            addCriterion("freq is not null");
            return (Criteria) this;
        }

        public Criteria andFreqEqualTo(Float value) {
            addCriterion("freq =", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqNotEqualTo(Float value) {
            addCriterion("freq <>", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqGreaterThan(Float value) {
            addCriterion("freq >", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqGreaterThanOrEqualTo(Float value) {
            addCriterion("freq >=", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqLessThan(Float value) {
            addCriterion("freq <", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqLessThanOrEqualTo(Float value) {
            addCriterion("freq <=", value, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqIn(List<Float> values) {
            addCriterion("freq in", values, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqNotIn(List<Float> values) {
            addCriterion("freq not in", values, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqBetween(Float value1, Float value2) {
            addCriterion("freq between", value1, value2, "freq");
            return (Criteria) this;
        }

        public Criteria andFreqNotBetween(Float value1, Float value2) {
            addCriterion("freq not between", value1, value2, "freq");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smoothdou
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 06 09:43:35 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smoothdou
     *
     * @mbggenerated Wed Jun 06 09:43:35 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}