package com.example.infoRetrieval.pojo;

public class StopTerm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_term.term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    private String term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_term.term
     *
     * @return the value of stop_term.term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_term.term
     *
     * @param term the value for stop_term.term
     *
     * @mbggenerated Tue May 01 12:51:09 CST 2018
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }
}