package com.example.infoRetrieval.pojo;

public class WTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tbl.term
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    private String term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tbl.doc
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    private String doc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_tbl.res
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    private Double res;

    public WTbl(String term, String doc, double v) {
        this.doc = doc;
        this.res = v;
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_tbl.term
     *
     * @return the value of w_tbl.term
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_tbl.term
     *
     * @param term the value for w_tbl.term
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_tbl.doc
     *
     * @return the value of w_tbl.doc
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public String getDoc() {
        return doc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_tbl.doc
     *
     * @param doc the value for w_tbl.doc
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public void setDoc(String doc) {
        this.doc = doc == null ? null : doc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_tbl.res
     *
     * @return the value of w_tbl.res
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public Double getRes() {
        return res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_tbl.res
     *
     * @param res the value for w_tbl.res
     *
     * @mbggenerated Sat Jun 02 13:55:56 GMT+08:00 2018
     */
    public void setRes(Double res) {
        this.res = res;
    }
}